export const publicRoutes = [
  '/',
  '/about',
  '/services',
  '/services/job-consultancy',
  '/services/permanent-staffing',
  '/services/temporary-staffing',
  '/services/contract-staffing',
  '/services/hr-outsourcing',
  '/services/campus-recruitment-drive',
  '/services/lean-consulting-services',
  '/services/corporate-events',
  '/services/iso-certification-support',
  '/services/six-sigma-training-consulting',
  '/services/housekeeping-services',
  '/services/indoor-outdoor-catering-services',
  '/services/complete-plant-setup-support',
  '/services/medical-check-up-coordination',
  '/services/wedding-events',
  '/services/exhibition-events',
  '/services/background-verification',
  '/campus-drive',
  '/cv-writing',
  '/jobs',
  '/blogs',
  '/contact',
  '/events',
  '/catering',
  '/testimonials',
  '/brochures',
  '/terms',
  '/privacy',
]

export const excludedSitemapPatterns = [
  /^\/admin(\/|$)/,
  /^\/dashboard(\/|$)/,
  /^\/employer(\/|$)/,
  /^\/login\/?$/,
  /^\/register\/?$/,
  /^\/api(\/|$)/,
]

export const shouldIncludeInSitemap = (path = '/') =>
  !excludedSitemapPatterns.some((pattern) => pattern.test(path))
